title: Hal's Musings
author: Hal Rodriguez
email: hr2003@nyu.edu
description: Hal's NYU ITP blog documenting assigments, experiments, explorations, & projects.
theme: minima

# social links
# https://github.com/jekyll/minima#social-networks
github_username:  halr # DO NOT include the @ character, or else the build will fail!
#linkedin_username: jekyll
instagram_username: amped_atelier
#twitter_username: amped_atelier # DO NOT include the @ character, or else the build will fail!
#youtube: jekyll
youtube_channel: UCGeZbuoySYh9jiNyxq_dClw
youtube_channel_name: Amped Atelier

show_excerpts: true # set to false to remove excerpts on the homepage

header_pages:
  - about.md
  - intangible.md
  - mixd.md

# Enabling comments (via Disqus)
disqus:
  shortname: hals-musings # https://help.disqus.com/en/articles/1717111-what-s-a-shortname