title: Hal's Musings
author: Hal Rodriguez
email: hr2003@nyu.edu
description: experiments, explorations, & projects
theme: minima

# social links
github_username:  halr # DO NOT include the @ character, or else the build will fail!
#linkedin_username: jekyll
#instagram_username: thaumatomane
#youtube_username: jekyll
#twitter_username: halr66 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

header_pages:
  - about.md
  - intangible.md
  - mixd.md